
services:
  # Frontend
  taskora-frontend:
    build:
      context: ./taskora-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Маппинг порта frontend
    networks:
      - default
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - default