apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-nginx
  labels:
    app.kubernetes.io/name: proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  default.conf: |-
    {{ tpl .Values.nginx.config . | nindent 4 }}
