spring.application.name=taskora-backend
server.port=8080

# ===============================
# DATABASE
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}

# ===============================
# SWAGGER
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:true}

# ===============================
# JWT / COOKIE
# ===============================
jwt.secret=${JWT_SECRET}
auth.session.seconds=${AUTH_SESSION_SECONDS}

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=${ACTUATOR_SHOW_DETAILS:never}
management.endpoint.health.probes.enabled=true
